import { normalizeText } from './units';

/** Supermarket aisles used to group the shopping list, in walking order. */
export const AISLES = [
  'produce',
  'bakery',
  'meat',
  'fish',
  'dairy',
  'frozen',
  'pantry',
  'spices',
  'drinks',
  'household',
  'other',
] as const;
export type Aisle = (typeof AISLES)[number];

export const AISLE_LABELS: Record<Aisle, { fr: string; en: string; emoji: string }> = {
  produce: { fr: 'Fruits & légumes', en: 'Fruit & vegetables', emoji: '🥕' },
  bakery: { fr: 'Boulangerie', en: 'Bakery', emoji: '🥖' },
  meat: { fr: 'Boucherie & charcuterie', en: 'Meat & deli', emoji: '🥩' },
  fish: { fr: 'Poissonnerie', en: 'Fish & seafood', emoji: '🐟' },
  dairy: { fr: 'Crèmerie & œufs', en: 'Dairy & eggs', emoji: '🧀' },
  frozen: { fr: 'Surgelés', en: 'Frozen', emoji: '🧊' },
  pantry: { fr: 'Épicerie', en: 'Pantry', emoji: '🥫' },
  spices: { fr: 'Épices & condiments', en: 'Spices & condiments', emoji: '🧂' },
  drinks: { fr: 'Boissons', en: 'Drinks', emoji: '🧃' },
  household: { fr: 'Maison', en: 'Household', emoji: '🧻' },
  other: { fr: 'Autres', en: 'Other', emoji: '🛒' },
};

/**
 * Keyword → aisle. Keys are accent-free and lower-case; a keyword matches a
 * whole word (or word prefix for plurals) of the ingredient name.
 * Order matters: the first matching rule wins, so specific terms come first.
 */
const RULES: [Aisle, string[]][] = [
  ['frozen', ['surgele', 'surgeles', 'glace', 'sorbet', 'frozen', 'ice cream']],
  [
    'spices',
    [
      'sel',
      'poivre',
      'epice',
      'epices',
      'curry',
      'cumin',
      'paprika',
      'cannelle',
      'muscade',
      'curcuma',
      'piment',
      'herbes de provence',
      'thym seche',
      'laurier',
      'vanille',
      'moutarde',
      'ketchup',
      'mayonnaise',
      'vinaigre',
      'sauce soja',
      'soja',
      'bouillon',
      'cube',
      'pate de curry',
      'harissa',
      'gingembre moulu',
      'origan',
      'salt',
      'pepper',
      'spice',
      'cinnamon',
      'nutmeg',
      'turmeric',
      'chili',
      'mustard',
      'vinegar',
      'soy sauce',
      'stock',
      'curry paste',
      'oregano',
      'bay leaf',
      'garam masala',
      'ras el hanout',
    ],
  ],
  [
    'fish',
    [
      'poisson',
      'saumon',
      'thon',
      'cabillaud',
      'crevette',
      'crevettes',
      'moules',
      'colin',
      'truite',
      'sardine',
      'maquereau',
      'lieu',
      'dorade',
      'bar',
      'calamar',
      'noix de saint-jacques',
      'saint-jacques',
      'fish',
      'salmon',
      'tuna',
      'cod',
      'prawn',
      'prawns',
      'shrimp',
      'mussels',
      'trout',
      'mackerel',
      'squid',
      'scallops',
      'anchois',
      'anchovies',
    ],
  ],
  [
    'meat',
    [
      'poulet',
      'boeuf',
      'veau',
      'porc',
      'agneau',
      'dinde',
      'canard',
      'lardons',
      'lardon',
      'jambon',
      'bacon',
      'saucisse',
      'saucisses',
      'chorizo',
      'steak',
      'viande',
      'hache',
      'escalope',
      'filet mignon',
      'cuisse',
      'cuisses',
      'blanc de poulet',
      'blancs de poulet',
      'merguez',
      'rôti',
      'roti',
      'chicken',
      'beef',
      'veal',
      'pork',
      'lamb',
      'turkey',
      'duck',
      'ham',
      'sausage',
      'sausages',
      'mince',
      'minced',
      'meat',
      'lardons fumes',
    ],
  ],
  [
    'dairy',
    [
      'lait',
      'beurre',
      'creme',
      'creme fraiche',
      'yaourt',
      'yaourts',
      'fromage',
      'gruyere',
      'emmental',
      'parmesan',
      'mozzarella',
      'comte',
      'chevre',
      'feta',
      'ricotta',
      'mascarpone',
      'oeuf',
      'oeufs',
      'jaune',
      'jaunes',
      'blanc',
      'blancs',
      'fromage blanc',
      'petit suisse',
      'milk',
      'butter',
      'cream',
      'yogurt',
      'yoghurt',
      'cheese',
      'egg',
      'eggs',
      'cheddar',
      'creme epaisse',
      'pate brisee',
      'pate feuilletee',
      'pate sablee',
      'pate a pizza',
      'puff pastry',
      'shortcrust',
    ],
  ],
  [
    'bakery',
    [
      'pain',
      'baguette',
      'brioche',
      'pain de mie',
      'croissant',
      'tortilla',
      'tortillas',
      'chapelure',
      'bread',
      'breadcrumbs',
      'bun',
      'buns',
      'pita',
    ],
  ],
  [
    'drinks',
    [
      'vin',
      'biere',
      'jus',
      'eau gazeuse',
      'cidre',
      'rhum',
      'cognac',
      'porto',
      'wine',
      'beer',
      'juice',
      'rum',
      'soda',
      'cafe',
      'the',
      'coffee',
      'tea',
    ],
  ],
  [
    'produce',
    [
      'pomme',
      'pommes',
      'poire',
      'banane',
      'citron',
      'citrons',
      'orange',
      'fraise',
      'fraises',
      'framboise',
      'framboises',
      'myrtille',
      'myrtilles',
      'abricot',
      'peche',
      'cerise',
      'raisin',
      'mangue',
      'ananas',
      'kiwi',
      'avocat',
      'tomate',
      'tomates',
      'carotte',
      'carottes',
      'oignon',
      'oignons',
      'echalote',
      'echalotes',
      'ail',
      'poireau',
      'poireaux',
      'courgette',
      'courgettes',
      'aubergine',
      'aubergines',
      'poivron',
      'poivrons',
      'champignon',
      'champignons',
      'salade',
      'laitue',
      'epinard',
      'epinards',
      'chou',
      'brocoli',
      'chou-fleur',
      'haricot vert',
      'haricots verts',
      'petits pois',
      'pomme de terre',
      'pommes de terre',
      'patate',
      'patate douce',
      'navet',
      'celeri',
      'concombre',
      'radis',
      'betterave',
      'potiron',
      'butternut',
      'citrouille',
      'fenouil',
      'asperge',
      'asperges',
      'persil',
      'coriandre',
      'basilic',
      'menthe',
      'ciboulette',
      'thym',
      'romarin',
      'aneth',
      'estragon',
      'gingembre',
      'citron vert',
      'lime',
      'apple',
      'apples',
      'pear',
      'banana',
      'lemon',
      'lemons',
      'strawberries',
      'raspberries',
      'blueberries',
      'tomato',
      'tomatoes',
      'carrot',
      'carrots',
      'onion',
      'onions',
      'shallot',
      'shallots',
      'garlic',
      'leek',
      'zucchini',
      'courgette',
      'eggplant',
      'aubergine',
      'pepper',
      'bell pepper',
      'mushroom',
      'mushrooms',
      'lettuce',
      'spinach',
      'cabbage',
      'broccoli',
      'cauliflower',
      'green beans',
      'peas',
      'potato',
      'potatoes',
      'sweet potato',
      'celery',
      'cucumber',
      'pumpkin',
      'squash',
      'parsley',
      'coriander',
      'cilantro',
      'basil',
      'mint',
      'chives',
      'thyme',
      'rosemary',
      'dill',
      'ginger',
      'avocado',
      'fruit',
      'fruits',
      'legume',
      'legumes',
    ],
  ],
  [
    'pantry',
    [
      'farine',
      'sucre',
      'huile',
      'riz',
      'pates',
      'spaghetti',
      'penne',
      'tagliatelle',
      'lentilles',
      'pois chiches',
      'haricots',
      'semoule',
      'quinoa',
      'boulgour',
      'levure',
      'maizena',
      'fecule',
      'chocolat',
      'cacao',
      'miel',
      'confiture',
      'amande',
      'amandes',
      'noisette',
      'noisettes',
      'noix',
      'pignons',
      'raisins secs',
      'lait de coco',
      'creme de coco',
      'conserve',
      'tomates concassees',
      'coulis',
      'concentre de tomate',
      'olive',
      'olives',
      'cornichon',
      'cornichons',
      'cafe',
      'flocons',
      'avoine',
      'cereales',
      'sirop',
      'flour',
      'sugar',
      'oil',
      'rice',
      'pasta',
      'noodles',
      'lentils',
      'chickpeas',
      'beans',
      'couscous',
      'yeast',
      'baking powder',
      'cornstarch',
      'chocolate',
      'cocoa',
      'honey',
      'jam',
      'almonds',
      'hazelnuts',
      'walnuts',
      'nuts',
      'coconut milk',
      'oats',
      'syrup',
      'canned',
      'tomato paste',
    ],
  ],
  [
    'household',
    [
      'papier',
      'essuie-tout',
      'sac',
      'sacs',
      'lessive',
      'liquide vaisselle',
      'eponge',
      'aluminium',
      'film',
      'paper',
      'foil',
      'detergent',
      'sponge',
    ],
  ],
];

const compiled = RULES.map(([aisle, words]) => ({
  aisle,
  res: words.map((w) => new RegExp(`(^|[^a-z])${w.replace(/[-]/g, '[- ]')}s?($|[^a-z])`)),
}));

/** Guesses the supermarket aisle of an ingredient from its name. */
export function guessAisle(name: string): Aisle {
  const n = normalizeText(name);
  // Multi-word ingredients like "lait de coco" must beat "lait": test the longest keyword first.
  let best: { aisle: Aisle; len: number } | null = null;
  for (const { aisle, res } of compiled) {
    for (const re of res) {
      const m = re.exec(n);
      if (m && (!best || m[0].length > best.len)) best = { aisle, len: m[0].length };
    }
  }
  return best?.aisle ?? 'other';
}
