// Generates src/ui/icons.generated.ts from Material Symbols Rounded (Apache-2.0).
// Usage: npm run icons:gen  (edit the NAMES list below to add icons)
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';

const require = createRequire(import.meta.url);
const base = join(dirname(require.resolve('@material-symbols/svg-400/package.json')), 'rounded');

const NAMES = [
  'add',
  'arrow_back',
  'arrow_forward',
  'check',
  'check_circle',
  'close',
  'delete',
  'edit',
  'favorite',
  'search',
  'filter_list',
  'grid_view',
  'view_list',
  'casino',
  'more_vert',
  'share',
  'star',
  'timer',
  'restaurant',
  'menu_book',
  'cooking',
  'soup_kitchen',
  'calendar_month',
  'shopping_cart',
  'settings',
  'link',
  'content_paste',
  'photo_camera',
  'image',
  'schedule',
  'skillet',
  'local_fire_department',
  'group',
  'remove',
  'play_arrow',
  'pause',
  'stop',
  'replay',
  'kitchen',
  'collections_bookmark',
  'bookmark',
  'label',
  'download',
  'upload',
  'backup',
  'settings_backup_restore',
  'palette',
  'dark_mode',
  'light_mode',
  'brightness_auto',
  'language',
  'info',
  'send',
  'playlist_add',
  'chevron_left',
  'chevron_right',
  'keyboard_arrow_down',
  'keyboard_arrow_up',
  'drag_indicator',
  'notifications',
  'open_in_new',
  'undo',
  'text_snippet',
  'stars',
  'lightbulb',
  'sort',
  'tune',
  'shopping_basket',
  'event',
  'fullscreen',
  'volume_up',
  'history',
  'folder_zip',
  'warning',
  'done_all',
  'remove_shopping_cart',
  'format_list_numbered',
  'checklist',
  'notes',
  'sticky_note',
  'public',
  'visibility',
  'sell',
];

const out = {};
for (const n of NAMES) {
  for (const [key, file] of [
    [n, `${n}.svg`],
    [`${n}_fill`, `${n}-fill.svg`],
  ]) {
    try {
      const svg = readFileSync(join(base, file), 'utf8');
      out[key] = [...svg.matchAll(/ d="([^"]+)"/g)].map((m) => m[1]).join(' ');
    } catch {
      if (key === n) throw new Error(`Icon not found: ${n}`);
    }
  }
}

const body = Object.entries(out)
  .map(([k, v]) => `  ${k}: '${v}',`)
  .join('\n');
writeFileSync(
  'src/ui/icons.generated.ts',
  `// AUTO-GENERATED by scripts/gen-icons.mjs — Material Symbols Rounded (Apache-2.0). Do not edit.\nexport const ICONS = {\n${body}\n} as const;\n\nexport type IconName = keyof typeof ICONS;\n`,
);
console.log(`Generated ${Object.keys(out).length} icons`);
